<html>
<head>
<title>Error Handling in JavaScript Explained With Examples</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">用例子解释JavaScript中的错误处理</h1>
<blockquote>原文：<a href="https://javascript.plainenglish.io/error-handling-in-javascript-explained-with-examples-bab0868ed879?source=collection_archive---------11-----------------------#2021-04-19">https://javascript.plainenglish.io/error-handling-in-javascript-explained-with-examples-bab0868ed879?source=collection_archive---------11-----------------------#2021-04-19</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><div class=""><h2 id="0db7" class="pw-subtitle-paragraph jn ip iq bd b jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke dk translated">了解JavaScript中错误处理的基础知识。</h2></div><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi kf"><img src="../Images/69db51e0337d4386d8fb1016f18e071d.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*CCqKQ-RjIcD0z6kt"/></div></div><figcaption class="kr ks gj gh gi kt ku bd b be z dk">Photo by <a class="ae kv" href="https://unsplash.com/@blakeconnally?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Blake Connally</a> on <a class="ae kv" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a></figcaption></figure><p id="2ce2" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">作为一名开发人员，错误是最令人讨厌的事情。这是编码过程的一部分，你会习惯的。在JavaScript中，当访问未定义的变量或函数时，很多时候你会遇到运行时错误。</p><p id="bdc0" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">幸运的是，JavaScript提供了一种处理运行时错误的方法。语句<code class="fe ls lt lu lv b">try</code>、<code class="fe ls lt lu lv b">catch</code>、<code class="fe ls lt lu lv b">throw</code>和<code class="fe ls lt lu lv b">finally</code>就是一个很好的例子。例如，在处理异步操作以及处理来自其他资源的数据或用户输入时，您可以使用这些方法轻松处理错误。</p><p id="769c" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在本文中，我们将学习JavaScript中错误处理的基础知识。所以让我们开始吧。</p></div><div class="ab cl lw lx hu ly" role="separator"><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb"/></div><div class="ij ik il im in"><h1 id="8aa1" class="md me iq bd mf mg mh mi mj mk ml mm mn jw mo jx mp jz mq ka mr kc ms kd mt mu bi translated">try和catch语句</h1><p id="ade0" class="pw-post-body-paragraph kw kx iq ky b kz mv jr lb lc mw ju le lf mx lh li lj my ll lm ln mz lp lq lr ij bi translated">JavaScript中的语句<code class="fe ls lt lu lv b">try</code>允许我们在代码块执行时检查其中的错误。</p><pre class="kg kh ki kj gt na lv nb nc aw nd bi"><span id="fccf" class="ne me iq lv b gy nf ng l nh ni"><strong class="lv ir">try </strong>{<br/>  //Your code here.<em class="nj"><br/></em>}</span></pre><p id="a9b9" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">另一方面，语句<code class="fe ls lt lu lv b">catch</code>允许您处理语句<code class="fe ls lt lu lv b">try</code>中出现的错误。</p><p id="6f50" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">这里有一个例子:</p><pre class="kg kh ki kj gt na lv nb nc aw nd bi"><span id="42ae" class="ne me iq lv b gy nf ng l nh ni"><strong class="lv ir">try </strong>{<br/>  //Your code here.<em class="nj"><br/></em>}<strong class="lv ir">catch(<em class="nj">err</em>)</strong> {<br/>  //Code for handling the error.<em class="nj"><br/></em>}</span></pre><p id="a4ab" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">如您所见，<code class="fe ls lt lu lv b">catch</code>接受了一个错误参数<code class="fe ls lt lu lv b">err</code>。你可以给它取任何你想要的名字。它是一个对象，我们可以访问它来获得关于错误的信息。</p><p id="6183" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">对象<code class="fe ls lt lu lv b">err</code>有一些有用的属性，我们可以使用点符号来访问这些属性以获得错误信息。</p><pre class="kg kh ki kj gt na lv nb nc aw nd bi"><span id="674e" class="ne me iq lv b gy nf ng l nh ni"><strong class="lv ir">try </strong>{<br/>  //Your code here.<em class="nj"><br/></em>}<strong class="lv ir">catch(<em class="nj">err</em>)</strong> {<br/>  console.log(<strong class="lv ir">err.name</strong>); //error name.<br/>  console.log(<strong class="lv ir">err.message</strong>); //error message.<br/>  console.log(<strong class="lv ir">err.stack</strong>); //Where the error occured<br/>}</span></pre><p id="cf9b" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">让我们看一个真实的例子，向您展示JavaScript中的错误处理是如何工作的:</p><p id="d730" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在下面的例子中，我们将调用一个我们还没有定义的函数<code class="fe ls lt lu lv b">getData()</code>来引起一个错误。因此，我们将使用语句<code class="fe ls lt lu lv b">try</code>和<code class="fe ls lt lu lv b">catch</code>来检查和处理该错误。</p><p id="b28a" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">下面是一个例子:</p><pre class="kg kh ki kj gt na lv nb nc aw nd bi"><span id="03dc" class="ne me iq lv b gy nf ng l nh ni"><strong class="lv ir">try</strong>{<br/>    console.log('Hello World');<br/>   <strong class="lv ir"> getData()</strong>; //Calling a function that we haven't defined.<br/>}<br/><strong class="lv ir">catch(err)</strong>{<br/>    console.log(`${<strong class="lv ir">err.name</strong>}: ${<strong class="lv ir">err.message</strong>}`)<br/>}</span><span id="9432" class="ne me iq lv b gy nk ng l nh ni">//output:<br/>Hello World<br/>ReferenceError: getData is not defined</span></pre><p id="f7e6" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">如你所见，语句<code class="fe ls lt lu lv b">try</code>发现了一个错误(调用一个未定义的函数<code class="fe ls lt lu lv b">getData()</code>)。当错误发生在try语句中时，它会自动在catch语句中得到处理。如果没有错误，catch语句中不会发生任何事情。</p><p id="0b07" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在上面的例子中，我们使用了语句<code class="fe ls lt lu lv b">catch</code>来捕获错误，并在控制台中输出其名称和消息。</p></div><div class="ab cl lw lx hu ly" role="separator"><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb"/></div><div class="ij ik il im in"><h1 id="4b84" class="md me iq bd mf mg mh mi mj mk ml mm mn jw mo jx mp jz mq ka mr kc ms kd mt mu bi translated">throw和finally语句</h1><p id="7040" class="pw-post-body-paragraph kw kx iq ky b kz mv jr lb lc mw ju le lf mx lh li lj my ll lm ln mz lp lq lr ij bi translated">语句<code class="fe ls lt lu lv b">throw</code>允许您创建自定义错误。您可以随时使用它来抛出错误。</p><p id="603e" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">这里有一个例子:</p><pre class="kg kh ki kj gt na lv nb nc aw nd bi"><span id="6875" class="ne me iq lv b gy nf ng l nh ni"><strong class="lv ir">throw new SyntaxError</strong>("syntax error has occured");</span><span id="ff50" class="ne me iq lv b gy nk ng l nh ni">//or:<br/><strong class="lv ir">throw Error</strong>("error has occured");</span><span id="f10c" class="ne me iq lv b gy nk ng l nh ni">//or:<br/><strong class="lv ir">throw </strong>"this is a custom error"</span></pre><p id="e009" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">另一方面，不管有没有错误，语句<code class="fe ls lt lu lv b">finally</code>都允许您运行代码。无论try和catch语句的结果如何，您放在语句<code class="fe ls lt lu lv b">finally</code>中的代码都将一直运行。</p><p id="0a62" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">让我们来看一个简单的例子，将<code class="fe ls lt lu lv b">try</code>、<code class="fe ls lt lu lv b">catch</code>、<code class="fe ls lt lu lv b">throw</code>和<code class="fe ls lt lu lv b">finally</code>一起使用:</p><p id="b606" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">下面的例子将检查一个名为<code class="fe ls lt lu lv b">user</code>的对象是否有一个truthy name值。如果没有，我们将使用语句<code class="fe ls lt lu lv b">throw</code>创建一个错误对象。我们将在catch语句中处理和访问错误对象。</p><pre class="kg kh ki kj gt na lv nb nc aw nd bi"><span id="63ad" class="ne me iq lv b gy nf ng l nh ni">let user = {<br/>    name: "",<br/>    age: 19<br/>}</span><span id="7c95" class="ne me iq lv b gy nk ng l nh ni"><strong class="lv ir">try</strong>{<br/>   if(!user.name){<br/>      <strong class="lv ir">throw new ReferenceError</strong>("The user doesn't have a name property");<br/>    }<br/>}<strong class="lv ir">catch(err)</strong>{<br/>    console.log("No name: " + <strong class="lv ir">err.message</strong>);<br/>}<strong class="lv ir">finally</strong>{<br/>    console.log("This will always run.");<br/>}</span><span id="410c" class="ne me iq lv b gy nk ng l nh ni">//output:<br/>No name: The user doesn't have a name property<br/>This will always run.</span></pre><p id="97e1" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">如您所见，通过使用catch语句，我们访问并打印了使用<code class="fe ls lt lu lv b">throw</code>语句创建的错误。</p><p id="f32c" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">您还应该记住，这些语句只适用于运行时错误(可以执行的代码)。如果代码语法错误，它们就不会工作。</p></div><div class="ab cl lw lx hu ly" role="separator"><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb"/></div><div class="ij ik il im in"><h1 id="e5d7" class="md me iq bd mf mg mh mi mj mk ml mm mn jw mo jx mp jz mq ka mr kc ms kd mt mu bi translated">承诺和异步/等待</h1><p id="227a" class="pw-post-body-paragraph kw kx iq ky b kz mv jr lb lc mw ju le lf mx lh li lj my ll lm ln mz lp lq lr ij bi translated">大多数时候，您会希望将<code class="fe ls lt lu lv b">try</code>和<code class="fe ls lt lu lv b">catch</code>与承诺和async/await混合起来进行错误处理。</p><p id="11a7" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">这里有一个例子:</p><pre class="kg kh ki kj gt na lv nb nc aw nd bi"><span id="0f39" class="ne me iq lv b gy nf ng l nh ni">const ourPromise = <strong class="lv ir">new Promise</strong>((resolve, reject)=&gt;{<br/>    setTimeout(()=&gt; reject("This is an error"), 2000)<br/>});</span><span id="8aee" class="ne me iq lv b gy nk ng l nh ni">const testPromise = <strong class="lv ir">async </strong>()=&gt;{<br/>    <strong class="lv ir">try</strong>{<br/>        let data = <strong class="lv ir">await </strong>ourPromise;<br/>    }<strong class="lv ir">catch(err</strong>){<br/>        console.error(err); <br/>    }<br/>}</span></pre><p id="235f" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在上面的例子中，当承诺被拒绝时，错误被捕获并显示在控制台中。try语句检查承诺是否被拒绝。如果是这样，catch语句将捕获错误。</p></div><div class="ab cl lw lx hu ly" role="separator"><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb mc"/><span class="lz bw bk ma mb"/></div><div class="ij ik il im in"><h1 id="8e86" class="md me iq bd mf mg mh mi mj mk ml mm mn jw mo jx mp jz mq ka mr kc ms kd mt mu bi translated">结论</h1><p id="7bc9" class="pw-post-body-paragraph kw kx iq ky b kz mv jr lb lc mw ju le lf mx lh li lj my ll lm ln mz lp lq lr ij bi translated">错误处理在JavaScript中非常重要。所以，如果你想更好地处理错误，你需要练习所有这些语句。</p><p id="b300" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">感谢您阅读这篇文章。希望你觉得有用。</p><p id="4ab6" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated"><strong class="ky ir">更多阅读</strong></p><div class="nl nm gp gr nn no"><a rel="noopener  ugc nofollow" target="_blank" href="/how-to-customize-your-vscode-for-front-end-web-development-b80c8eb562d1"><div class="np ab fo"><div class="nq ab nr cl cj ns"><h2 class="bd ir gy z fp nt fr fs nu fu fw ip bi translated">如何为前端Web开发定制VSCode</h2><div class="nv l"><h3 class="bd b gy z fp nt fr fs nu fu fw dk translated">定制您的VSCode，使其更好地为您服务。</h3></div><div class="nw l"><p class="bd b dl z fp nt fr fs nu fu fw dk translated">javascript.plainenglish.io</p></div></div><div class="nx l"><div class="ny l nz oa ob nx oc kp no"/></div></div></a></div><p id="aa89" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated"><em class="nj">更多内容请看</em><a class="ae kv" href="http://plainenglish.io/" rel="noopener ugc nofollow" target="_blank"><em class="nj">plain English . io</em></a></p></div></div>    
</body>
</html>